### ISSUE TITLE
Theme not applied on Eclipse Photon start

### ISSUE THREAD

**Issue by alostale** [eclipse-color-theme/eclipse-color-theme#268]
Using Eclipse Photon (4.8.0) with Dark theme and Eclipse Color Theme 1.0.0.201410260308.

Each time I open my workspace, default Eclipse themes are applied. If I open Color Theme in preferences I see selected the theme I previously set, if I apply it again, the colors look as they should.

Just after opening Eclipse:
![Just open](https://user-images.githubusercontent.com/547258/43626939-679c73cc-96f4-11e8-8220-758ae1aa5933.png)

I open Color Theme preferences and I correctly see Obsidian theme selected
![Preferences](https://user-images.githubusercontent.com/547258/43627051-ea9de76a-96f4-11e8-9713-518ce689a855.png)

I need to reapply again to properly see it in editors:
![selection_277](https://user-images.githubusercontent.com/547258/43627074-06f9dcac-96f5-11e8-8a68-5f31cd705996.png)

**Comment by ipkpjersi** [comment]
I was NOT able to replicate this. I am using Ubuntu 16.04 with Eclipse 4.8 Photon with Dark theme and Eclipse Color Theme 1.0.0.201410260308 using Java 8 I believe, and when I set my theme to Sublime text 2 and restarted, it was still correctly using Sublime text 2. Are you experiencing this with other color themes, or just Obsidian?

Edit: With further testing, I was NOT able to replicate this with Obsidian either. Everything seems to be working as expected.

**Comment by alostale** [comment]
I can reproduce it with any theme :(

**Comment by ipkpjersi** [comment]
What OS are you using? What Java version? What other plugins do you have?

**Comment by ipkpjersi** [comment]
I WAS able to reproduce this on Windows 10 64-Bit 1803 with Eclipse 4.8 Photon with Dark theme and Eclipse Color Theme 1.0.0.201410260308 using Java 8. It seems that this only happens with the Dark theme, and using reduced pallete does not help either. Since this seems to be an issue with only the Dark theme and since this project sadly seems to be abandonware since the 2 maintainers are gone, perhaps it might be worth raising an issue upstream with Eclipse and seeing if there is a bug with the Dark theme on Eclipse 4.8 Photon?

**Comment by ipkpjersi** [comment]
I WAS able to reproduce this on Windows 10 64-Bit 1803 with Eclipse 4.8 Photon with Dark theme and Eclipse Color Theme 1.0.0.201410260308 using Java 8. It seems that this only happens with the Dark theme, and using reduced palette does not help either. Since this seems to be an issue with only the Dark theme and since this project sadly seems to be abandonware since the 2 maintainers are gone, perhaps it might be worth raising an issue upstream with Eclipse and seeing if there is a bug with the Dark theme on Eclipse 4.8 Photon?

I know the maintainers are gone but it may be worth me pinging them just in case.

CC: @fhd 
CC: @rogerdudler

**Comment by ipkpjersi** [comment]
I WAS able to reproduce this on Windows 10 64-Bit 1803 with Eclipse 4.8 Photon with Dark theme and Eclipse Color Theme 1.0.0.201410260308 using Java 8. It seems that this only happens with the Dark theme, and using reduced palette does not help either. Since this seems to be an issue with only the Dark theme and since this project sadly seems to be abandonware since the 2 maintainers are gone, perhaps it might be worth raising an issue upstream with Eclipse and seeing if there is a bug with the Dark theme on Eclipse 4.8 Photon?

I know the maintainers are gone but it may be worth me pinging them just in case.

CC: @fhd 
CC: @rogerdudler 

If someone fixed this issue and approved PR 247, that'd be amazing and make this plugin so much more usable. Maybe the fork @rainysaturday has could be the new main repository if he's more active and they aren't active enough to add him as a maintainer here?

**Comment by alostale** [comment]
I'm reproducing it with:
* Ubuntu 18.04
* Eclipse Photon (4.8.0)
* Java SE Runtime Environment (build 1.8.0_171-b11)
* Eclipse Color Theme 1.0.0.201410260308.
* Eclipse theme Dark

Witth the same configuration, if I change Eclipse's them to Classic, the theme selected in Color Theme is kept as expected after restart.

**Comment by alostale** [comment]
I've reported this issue to Eclipse: https://bugs.eclipse.org/bugs/show_bug.cgi?id=537843

**Comment by alostale** [comment]
As (ugly) workaround I made it work by downloading the theme as [Eclipse Preferences](http://www.eclipsecolorthemes.org/?view=empty&action=download&theme=21&type=epf) and importing them in my workspace. In this way, settings are preserved.

**Comment by alostale** [comment]
Eclipse team rejected the issue I reported :cry: because they say it's not their fault but plugin's.

**Comment by rainysaturday** [comment]
Hi guys,
I haven't had much time working on this plugin as can be seen in my github history. This specific issue has existed for quite a while, but I haven't really looked into it.

I have been using the workaround documented here though and it has worked ok, except that you have to use Oomph:
https://github.com/eclipse-color-theme/eclipse-color-theme/issues/223#issuecomment-118787497

I'm still on Oxygen, so not sure if this works in photon but I suspect it will.

**Comment by alostale** [comment]
Duplicate of #223
